package keqing.gtqtcore.common.metatileentities.multi.multiblock.standard;

import codechicken.lib.render.CCRenderState;
import codechicken.lib.render.pipeline.IVertexOperation;
import codechicken.lib.texture.TextureUtils;
import codechicken.lib.vec.Cuboid6;
import codechicken.lib.vec.Matrix4;
import gregicality.multiblocks.api.metatileentity.GCYMRecipeMapMultiblockController;
import gregicality.multiblocks.api.render.GCYMTextures;
import gregicality.multiblocks.common.block.GCYMMetaBlocks;
import gregicality.multiblocks.common.block.blocks.BlockLargeMultiblockCasing;
import gregtech.api.GTValues;
import gregtech.api.capability.IMultipleTankHandler;
import gregtech.api.gui.GuiTextures;
import gregtech.api.gui.Widget;
import gregtech.api.gui.resources.TextureArea;
import gregtech.api.gui.widgets.ClickButtonWidget;
import gregtech.api.gui.widgets.WidgetGroup;
import gregtech.api.metatileentity.MetaTileEntity;
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.metatileentity.multiblock.IMultiblockPart;
import gregtech.api.metatileentity.multiblock.MultiblockAbility;
import gregtech.api.pattern.BlockPattern;
import gregtech.api.pattern.FactoryBlockPattern;
import gregtech.api.unification.material.Materials;
import gregtech.api.util.GTTransferUtils;
import gregtech.api.util.GTUtility;
import gregtech.api.util.RelativeDirection;
import gregtech.api.util.TextComponentUtil;
import gregtech.client.renderer.CubeRendererState;
import gregtech.client.renderer.ICubeRenderer;
import gregtech.client.renderer.cclop.ColourOperation;
import gregtech.client.renderer.cclop.LightMapOperation;
import gregtech.client.renderer.texture.Textures;
import gregtech.client.renderer.texture.cube.OrientedOverlayRenderer;
import gregtech.client.utils.BloomEffectUtil;
import gregtech.common.blocks.BlockGlassCasing;
import gregtech.common.blocks.MetaBlocks;
import keqing.gtqtcore.api.unification.GTQTMaterials;
import keqing.gtqtcore.client.textures.GTQTTextures;
import keqing.gtqtcore.common.block.GTQTMetaBlocks;
import keqing.gtqtcore.common.block.blocks.GTQTNuclearFusion;
import keqing.gtqtcore.common.block.blocks.GTQTTurbineCasing1;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.resources.I18n;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.util.DamageSource;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.EnumParticleTypes;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextComponentTranslation;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.fluids.FluidStack;
import org.apache.commons.lang3.ArrayUtils;

import javax.annotation.Nonnull;
import java.util.Collections;
import java.util.List;

import static gregtech.api.unification.material.Materials.Water;

public class MetaTileEntityCoolingTower extends MetaTileEntityBaseWithControl{
    int rate=1;
    Boolean work;
    public MetaTileEntityCoolingTower(ResourceLocation metaTileEntityId) {
        super(metaTileEntityId);
    }

    public MetaTileEntity createMetaTileEntity(IGregTechTileEntity iGregTechTileEntity) {
        return new MetaTileEntityCoolingTower(this.metaTileEntityId);
    }


    FluidStack WATER_STACK = Water.getFluid(1000*rate);

    FluidStack STEAM_STACK = GTQTMaterials.SteamExhaustGas.getFluid(50*rate);
    public boolean fillTanks(FluidStack stack, boolean simulate) {
        return GTTransferUtils.addFluidsToFluidHandler(getOutputFluidInventory(), simulate, Collections.singletonList(stack));
    }
    @Override
    protected void updateFormedValid() {
        IMultipleTankHandler inputTank = getInputFluidInventory();
        if (STEAM_STACK.isFluidStackIdentical(inputTank.drain(STEAM_STACK, false))) {
            inputTank.drain(STEAM_STACK, true);
            inputTank.drain(WATER_STACK, true);
            fillTanks(WATER_STACK,false);
            fillTanks(WATER_STACK,false);
        }
    }
    @Override
    @Nonnull
    protected Widget getFlexButton(int x, int y, int width, int height) {
        WidgetGroup group = new WidgetGroup(x, y, width, height);
        group.addWidget(new ClickButtonWidget(0, 0, 9, 18, "", this::decrementThreshold)
                .setButtonTexture(GuiTextures.BUTTON_THROTTLE_MINUS)
                .setTooltipText("减少流量"));
        group.addWidget(new ClickButtonWidget(9, 0, 9, 18, "", this::incrementThreshold)
                .setButtonTexture(GuiTextures.BUTTON_THROTTLE_PLUS)
                .setTooltipText("增大流量"));
        return group;
    }

    private void decrementThreshold(Widget.ClickData clickData) {
        this.rate = MathHelper.clamp(rate-5, 10, 100);

    }
    private void incrementThreshold(Widget.ClickData clickData) {

        this.rate = MathHelper.clamp(rate+5, 10, 100);

    }
    @Override
    protected void addDisplayText(List<ITextComponent> textList) {
        super.addDisplayText(textList);
        textList.add(new TextComponentTranslation("rate：%s ", rate));
    }


    @Override
    protected BlockPattern createStructurePattern() {
        return FactoryBlockPattern.start()
                .aisle("            aaaaaaa            ", "            aaaaaaa            ", "            bbbbbbb            ", "            bbbbbbb            ", "            bbbbbbb            ", "            bbbbbbb            ", "            bbbbbbb            ", "            bbbbbbb            ", "            bbbbbbb            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ")
                .aisle("         aaaa a a aaaa         ", "         aaaa a a aaaa         ", "         bbbb  e  bbbb         ", "         bbbb     bbbb         ", "         bbbb eee bbbb         ", "         bbbb efe bbbb         ", "         bbbb eee bbbb         ", "         bbbb     bbbb         ", "         bbbb     bbbb         ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ")
                .aisle("       aa    a a a    aa       ", "       aa    a a a    aa       ", "       bbb     e     bbb       ", "       bbb           bbb       ", "       bbb           bbb       ", "       bbb     f     bbb       ", "       bbb           bbb       ", "       bbb           bbb       ", "       bbb           bbb       ", "         dddd     dddd         ", "         dddd eee dddd         ", "         dddd efe dddd         ", "         dddd eee dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ")
                .aisle("      a a     a a     a a      ", "      a a     a a     a a      ", "      bb       e       bb      ", "      bb               bb      ", "      bb               bb      ", "      bb       f       bb      ", "      bb               bb      ", "      bb               bb      ", "      bb               bb      ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd     f     ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd eee dddd         ", "         dddd efe dddd         ", "         dddd eee dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "         ddddddddddddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ")
                .aisle("     a a       a       a a     ", "     a a       a       a a     ", "     bb        e        bb     ", "     bb                 bb     ", "     bb                 bb     ", "     bb        f        bb     ", "     bb                 bb     ", "     bb                 bb     ", "     bb                 bb     ", "      dd               dd      ", "      dd               dd      ", "      dd       f       dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd     f     ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd eee dddd         ", "         dddd efe dddd         ", "         dddd eee dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd eee dddd         ", "         dddd efe dddd         ", "         dddd eee dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "       dddddd     dddddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ")
                .aisle("    a a a     a a     a a a    ", "    a a a     a a     a a a    ", "    bb         e         bb    ", "    bb                   bb    ", "    bb                   bb    ", "    bb         f         bb    ", "    bb                   bb    ", "    bb                   bb    ", "    bb                   bb    ", "     dd                 dd     ", "     dd                 dd     ", "     dd        f        dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd       f       dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd     f     ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd     f     ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "      dddd           dddd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ")
                .aisle("   a a a       a       a a a   ", "   a a a       a       a a a   ", "   bb          e          bb   ", "   bb                     bb   ", "   bb                     bb   ", "   bb          f          bb   ", "   bb                     bb   ", "   bb                     bb   ", "   bb                     bb   ", "    dd                   dd    ", "    dd                   dd    ", "    dd         f         dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd        f        dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd       f       dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd       f       dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "     ddd               ddd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ")
                .aisle("  a a a a     a a     a a a a  ", "  a a a a     a a     a a a a  ", "  bb           e           bb  ", "  bb                       bb  ", "  bb                       bb  ", "  bb           f           bb  ", "  bb                       bb  ", "  bb                       bb  ", "  bb                       bb  ", "   dd                     dd   ", "   dd                     dd   ", "   dd          f          dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd         f         dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd        f        dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd        f        dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "    ddd                 ddd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ")
                .aisle("  aa a a a     a     a a a aa  ", "  aa a a a     a     a a a aa  ", "  b            e            b  ", "  b                         b  ", "  b                         b  ", "  b            f            b  ", "  b                         b  ", "  b                         b  ", "  b                         b  ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ", "   dd          f          d    ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd         f         d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "    dd         f         d     ", "    dd                   d     ", "    dd                   d     ", "    dd                   d     ", "   ddd                   dd    ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ", "   dd                     d    ")
                .aisle(" a      a a   a a   a a      a ", " a      a a   a a   a a      a ", " bb            e            bb ", " bb                         bb ", " bb                         bb ", " bb            f            bb ", " bb                         bb ", " bb                         bb ", " bb                         bb ", "  dd                       dd  ", "  dd                       dd  ", "  dd           f           dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ", "   d           f          dd   ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d          f         dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "    d          f         dd    ", "    d                    dd    ", "    d                    dd    ", "    d                    dd    ", "   dd                    ddd   ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ", "   d                      dd   ")
                .aisle(" a       a a   a   a a       a ", " a       a a   a   a a       a ", " b             e             b ", " b                           b ", " b                           b ", " b             f             b ", " b                           b ", " b                           b ", " b                           b ", "  d                         d  ", "  d                         d  ", "  d            f            d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "   dd                     dd   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ")
                .aisle(" a        a a a a a a        a ", " a        a a a a a a        a ", " b             e             b ", " b                           b ", " b                           b ", " b             f             b ", " b                           b ", " b                           b ", " b                           b ", "  d                         d  ", "  d                         d  ", "  d            f            d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "   dd                     dd   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ")
                .aisle("aa         a a a a a         aa", "aa         a a a a a         aa", "bb             e             bb", "bb                           bb", "bb                           bb", "bb             f             bb", "bb                           bb", "bb                           bb", "bb                           bb", " dd                         dd ", " dd                         dd ", " dd            f            dd ", " dd                         dd ", " dd                         dd ", " dd                         dd ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd           f           dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd          f          dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd          f          dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "  ddd                     ddd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ")
                .aisle("a a         a a a a         a a", "a a         a a a a         a a", "b              e              b", "b                             b", "b                             b", "b              f              b", "b                             b", "b                             b", "b                             b", " d                           d ", " d                           d ", " d             f             d ", " d                           d ", " d                           d ", " d                           d ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d            f            d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "  dd                       dd  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ")
                .aisle("aa a a a a a a a a a a a a a aa", "aa a a a a a a a a a a a a a aa", "b             eee             b", "b             eee             b", "be            eee            eb", "be            efe            eb", "be            eee            eb", "b             eee             b", "b             eee             b", " d                           d ", " de                         ed ", " de            f            ed ", " de                         ed ", " d                           d ", " d                           d ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  de                       ed  ", "  de           f           ed  ", "  de                       ed  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   de                     ed   ", "   de          f          ed   ", "   de                     ed   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   de                     ed   ", "   de          f          ed   ", "   de                     ed   ", "   d                       d   ", "   d                       d   ", "  dd                       dd  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ")
                .aisle("a a a a a a a a a a a a a a a a", "a a a a a a a a a a a a a a a a", "beeeeeeeeeeeeeefeeeeeeeeeeeeeeb", "b             efe             b", "be            efe            eb", "bfffffffffffffffffffffffffffffb", "be            efe            eb", "b             efe             b", "b             efe             b", " d             f             d ", " de            f            ed ", " dfffffffffffffffffffffffffffd ", " de            f            ed ", " d             f             d ", " d             f             d ", "  d            f            d  ", "  d            f            d  ", "  d            f            d  ", "  de           f           ed  ", "  dfffffffffffffffffffffffffd  ", "  de           f           ed  ", "  d            f            d  ", "  d            f            d  ", "  d            f            d  ", "  d            f            d  ", "   d           f           d   ", "   d           f           d   ", "   d           f           d   ", "   d           f           d   ", "   de          f          ed   ", "   dfffffffffffffffffffffffd   ", "   de          f          ed   ", "   d           f           d   ", "   d           f           d   ", "   d           f           d   ", "   d           f           d   ", "   d           f           d   ", "   d           f           d   ", "   d           f           d   ", "   d           f           d   ", "   de          f          ed   ", "   dfffffffffffffffffffffffd   ", "   de                     ed   ", "   d                       d   ", "   d                       d   ", "  dd                       dd  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ")
                .aisle("aa a a a a a a a a a a a a a aa", "aa a a a a a a a a a a a a a aa", "b             eee             b", "b             eee             b", "be            eee            eb", "be            efe            eb", "be            eee            eb", "b             eee             b", "b             eee             b", " d                           d ", " de                         ed ", " de            f            ed ", " de                         ed ", " d                           d ", " d                           d ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  de                       ed  ", "  de           f           ed  ", "  de                       ed  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   de                     ed   ", "   de          f          ed   ", "   de                     ed   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   de                     ed   ", "   de          f          ed   ", "   de                     ed   ", "   d                       d   ", "   d                       d   ", "  dd                       dd  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ")
                .aisle("a a         a a a a         a a", "a a         a a a a         a a", "b              e              b", "b                             b", "b                             b", "b              f              b", "b                             b", "b                             b", "b                             b", " d                           d ", " d                           d ", " d             f             d ", " d                           d ", " d                           d ", " d                           d ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d            f            d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "  dd                       dd  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ")
                .aisle("aa         a a a a a         aa", "aa         a a a a a         aa", "bb             e             bb", "bb                           bb", "bb                           bb", "bb             f             bb", "bb                           bb", "bb                           bb", "bb                           bb", " dd                         dd ", " dd                         dd ", " dd            f            dd ", " dd                         dd ", " dd                         dd ", " dd                         dd ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd           f           dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd          f          dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd          f          dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "  ddd                     ddd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ")
                .aisle(" a        a a a a a a        a ", " a        a a a a a a        a ", " b             e             b ", " b                           b ", " b                           b ", " b             f             b ", " b                           b ", " b                           b ", " b                           b ", "  d                         d  ", "  d                         d  ", "  d            f            d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "   dd                     dd   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ")
                .aisle(" a       a a   a   a a       a ", " a       a a   a   a a       a ", " b             e             b ", " b                           b ", " b                           b ", " b             f             b ", " b                           b ", " b                           b ", " b                           b ", "  d                         d  ", "  d                         d  ", "  d            f            d  ", "  d                         d  ", "  d                         d  ", "  d                         d  ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "   dd                     dd   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ")
                .aisle(" a      a a   a a   a a      a ", " a      a a   a a   a a      a ", " bb            e            bb ", " bb                         bb ", " bb                         bb ", " bb            f            bb ", " bb                         bb ", " bb                         bb ", " bb                         bb ", "  dd                       dd  ", "  dd                       dd  ", "  dd           f           dd  ", "  dd                       dd  ", "  dd                       dd  ", "  dd                       dd  ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd          f          dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd         f         dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd         f         dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "   ddd                   ddd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ")
                .aisle("  aa a a a     a     a a a aa  ", "  aa a a a     a     a a a aa  ", "  b            e            b  ", "  b                         b  ", "  b                         b  ", "  b            f            b  ", "  b                         b  ", "  b                         b  ", "  b                         b  ", "   d                       d   ", "   d                       d   ", "   d           f           d   ", "   d                       d   ", "   d                       d   ", "   d                       d   ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d          f          d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d         f         d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "     d         f         d     ", "     d                   d     ", "     d                   d     ", "     d                   d     ", "    dd                   dd    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ", "    d                     d    ")
                .aisle("  a a a a     a a     a a a a  ", "  a a a a     a a     a a a a  ", "  bb           e           bb  ", "  bb                       bb  ", "  bb                       bb  ", "  bb           f           bb  ", "  bb                       bb  ", "  bb                       bb  ", "  bb                       bb  ", "   dd                     dd   ", "   dd                     dd   ", "   dd          f          dd   ", "   dd                     dd   ", "   dd                     dd   ", "   dd                     dd   ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd         f         dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd        f        dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd        f        dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "    ddd                 ddd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ")
                .aisle("   a a a       a       a a a   ", "   a a a       a       a a a   ", "   bb          e          bb   ", "   bb                     bb   ", "   bb                     bb   ", "   bb          f          bb   ", "   bb                     bb   ", "   bb                     bb   ", "   bb                     bb   ", "    dd                   dd    ", "    dd                   dd    ", "    dd         f         dd    ", "    dd                   dd    ", "    dd                   dd    ", "    dd                   dd    ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd        f        dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd       f       dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd       f       dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "     ddd               ddd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ")
                .aisle("    a a a     a a     a a a    ", "    a a a     a a     a a a    ", "    bb         e         bb    ", "    bb                   bb    ", "    bb                   bb    ", "    bb         f         bb    ", "    bb                   bb    ", "    bb                   bb    ", "    bb                   bb    ", "     dd                 dd     ", "     dd                 dd     ", "     dd        f        dd     ", "     dd                 dd     ", "     dd                 dd     ", "     dd                 dd     ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd       f       dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd     f     ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd     f     ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "      dddd           dddd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ")
                .aisle("     a a       a       a a     ", "     a a       a       a a     ", "     bb        e        bb     ", "     bb                 bb     ", "     bb                 bb     ", "     bb        f        bb     ", "     bb                 bb     ", "     bb                 bb     ", "     bb                 bb     ", "      dd               dd      ", "      dd               dd      ", "      dd       f       dd      ", "      dd               dd      ", "      dd               dd      ", "      dd               dd      ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd     f     ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd eee dddd         ", "         dddd efe dddd         ", "         dddd eee dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd eee dddd         ", "         dddd efe dddd         ", "         dddd eee dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "       dddddd     dddddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ")
                .aisle("      a a     a a     a a      ", "      a a     a a     a a      ", "      bb       e       bb      ", "      bb               bb      ", "      bb               bb      ", "      bb       f       bb      ", "      bb               bb      ", "      bb               bb      ", "      bb               bb      ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd     f     ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "       ddd           ddd       ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd eee dddd         ", "         dddd efe dddd         ", "         dddd eee dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "         ddddddddddddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "         dddd     dddd         ")
                .aisle("       aa    a a a    aa       ", "       aa    a a a    aa       ", "       bbb     e     bbb       ", "       bbb           bbb       ", "       bbb           bbb       ", "       bbb     f     bbb       ", "       bbb           bbb       ", "       bbb           bbb       ", "       bbb           bbb       ", "         dddd     dddd         ", "         dddd eee dddd         ", "         dddd efe dddd         ", "         dddd eee dddd         ", "         dddd     dddd         ", "         dddd     dddd         ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ")
                .aisle("         aaaa a a aaaa         ", "         aaaa a a aaaa         ", "         bbbb  e  bbbb         ", "         bbbb     bbbb         ", "         bbbb eee bbbb         ", "         bbbb efe bbbb         ", "         bbbb eee bbbb         ", "         bbbb     bbbb         ", "         bbbb     bbbb         ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "            ddddddd            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ")
                .aisle("            aaaaaaa            ", "            aaaaaaa            ", "            bbbbbbb            ", "            bbbbbbb            ", "            bbbbbbb            ", "            bbb~bbb            ", "            bbbbbbb            ", "            bbbbbbb            ", "            bbbbbbb            ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ", "                               ")
                .where('~', selfPredicate())
                .where('b', states(getCasingState())
                        .or(abilities(MultiblockAbility.EXPORT_FLUIDS).setMaxGlobalLimited(8).setMinGlobalLimited(8))
                        .or(abilities(MultiblockAbility.IMPORT_FLUIDS).setMaxGlobalLimited(8).setMinGlobalLimited(8)))
                .where('a', states(MetaBlocks.FRAMES.get(Materials.StainlessSteel).getBlock(Materials.StainlessSteel)))
                .where('d', states(getCasingState()))
                .where('e', states(MetaBlocks.FRAMES.get(Materials.Titanium).getBlock(Materials.Titanium)))
                .where('f', states(getCasingState2()))
                .where(' ', any())
                .build();
    }

    private static IBlockState getCasingState() {
        return GTQTMetaBlocks.NUCLEAR_FUSION.getState(GTQTNuclearFusion.CasingType.NUCLEAR_FUSION_COOLING);
    }

    private static IBlockState getCasingState2() {
        return GTQTMetaBlocks.TURBINE_CASING1.getState(GTQTTurbineCasing1.TurbineCasingType.SA_TURBINE_CASING);
    }

    @Override
    public ICubeRenderer getBaseTexture(IMultiblockPart iMultiblockPart) {
        return GTQTTextures.NUCLEAR_FUSION_COOLING;
    }

    @Override
    protected OrientedOverlayRenderer getFrontOverlay() {
        return Textures.FUSION_REACTOR_OVERLAY;
    }


    @Override
    public List<ITextComponent> getDataInfo() {
        return Collections.emptyList();
    }

    public boolean hasMaintenanceMechanics() {
        return false;
    }

    public boolean hasMufflerMechanics() {
        return false;
    }
    @Override
    public void update() {
        super.update();
        pollutionParticles();

    }
    private void pollutionParticles() {
        BlockPos pos = this.getPos();
        EnumFacing facing = this.getFrontFacing().getOpposite();
        float xPos = facing.getXOffset() *15 + pos.getX() + 0.5F;
        float yPos = facing.getYOffset()  + pos.getY() + 0.25F+48;
        float zPos = facing.getZOffset() *15 + pos.getZ() + 0.5F;

        float ySpd = facing.getYOffset() * 0.7F + 0.7F + 0.8F * GTValues.RNG.nextFloat();

        for(int i=-3;i<4;i++)
            for(int j=-3;j<4;j++)
            {
                arunMufflerEffect(xPos, yPos, zPos, 0, ySpd, 0);
                arunMufflerEffect(xPos+i*3, yPos, zPos+j*3, 0, ySpd, 0);
                arunMufflerEffect(xPos+i*3, yPos, zPos, 0, ySpd, 0);
                arunMufflerEffect(xPos, yPos, zPos+j*3, 0, ySpd, 0);
            }
    }
    public void arunMufflerEffect(float xPos, float yPos, float zPos, float xSpd, float ySpd, float zSpd) {
        this.getWorld().spawnParticle(EnumParticleTypes.EXPLOSION_NORMAL, (double)xPos, (double)yPos, (double)zPos, (double)xSpd, (double)ySpd, (double)zSpd, new int[0]);
    }

}
