package keqing.gtqtcore.loaders.recipes;

import keqing.gtqtcore.loaders.recipes.chain.*;
import keqing.gtqtcore.loaders.recipes.chain.AcetyleneChain;
import keqing.gtqtcore.loaders.recipes.chain.AmmoniaChain;
import keqing.gtqtcore.loaders.recipes.chain.BZChain;
import keqing.gtqtcore.loaders.recipes.chain.BoronNitrideChain;
import keqing.gtqtcore.loaders.recipes.chain.BrineChain;
import keqing.gtqtcore.loaders.recipes.chain.DimethylformamideChain;
import keqing.gtqtcore.loaders.recipes.chain.EDTAChain;
import keqing.gtqtcore.loaders.recipes.chain.EtchingMaterialsChain;
import keqing.gtqtcore.loaders.recipes.chain.EthyleneGlycolChain;
import keqing.gtqtcore.loaders.recipes.chain.FantasyMaterials;
import keqing.gtqtcore.loaders.recipes.chain.FullereneChain;
import keqing.gtqtcore.loaders.recipes.chain.GalliumNitrideChain;
import keqing.gtqtcore.loaders.recipes.chain.GrapheneChain;
import keqing.gtqtcore.loaders.recipes.chain.HydrogenPeroxideChain;
import keqing.gtqtcore.loaders.recipes.chain.IsotopesChain;
import keqing.gtqtcore.loaders.recipes.chain.KaptonChain;
import keqing.gtqtcore.loaders.recipes.chain.KevlarChain;
import keqing.gtqtcore.loaders.recipes.chain.MagneticsChain;
import keqing.gtqtcore.loaders.recipes.chain.MethylamineChain;
import keqing.gtqtcore.loaders.recipes.chain.NanotubesChain;
import keqing.gtqtcore.loaders.recipes.circuits.*;
import keqing.gtqtcore.loaders.recipes.component.ComponentRecipes;
import keqing.gtqtcore.loaders.recipes.component.GTComponentsRemove;
import keqing.gtqtcore.loaders.recipes.handlers.*;

public class GTQTRecipesManager {
    private GTQTRecipesManager() {

    }
    public static void load() {
    }
    public static void init() {
        FakeToolRecipes.register();
        VanillaRecipes.register();
        DeltamethrinChain.init();
        RubbersChain.init();
        PlasticChain.init();
        CrystalRaw.init();
        BacteriaCulturesChain.init();
        ChemicalBath.init();
        FusionLoader.init();
        NeutralNetworkNexus.init();
        AirIntakeHatchRecipes.register();
        GCYMMultiblockRecipesOverwrite.init();
        BoronChain.init();
        EnzymesRecipes.init();
        ArgChain.init();
        ChipHelper.init();
        CoverRecipes.init();
        GTQTOreRecipeHandler.init();
        MolecularTransformer.init();
        StrontiumRadiumChain.init();
        AlgaeChain.init();
        FluidizedBedChain.init();
        AcidReactorRecipes.init();
        AntimatterGenerator.init();
        PPBChain.init();
        BioReactor.init();
        AirDistillation.init();
        SawmillChain.init();
        NaquadahFuelChain.init();
        LargeCircuitAssemblyLine.init();
        SodiumChain.init();
        ParticleAccelerator.init();
        CTABChain.init();
        DragonChain.init();
        CBDOPolycarbonateChain.init();
        SuperconductorRecipes.init();
        CaliforniumChain.init();
        TitanateChain.init();
        EnergyHatches.init();
        FluidHatches.init();
        MultiFluidHatches.init();
        ItemBuses.init();
        NuclearLine.init();
        OceanChain.init();
        MagnetoResonaticCircuits.init();
        VinylcinnamateChain.init();
        YeastLine.init();
        NaquadahChain.init();
        MachineCasing.init();
        Bittern.init();
        SimulatorHandler.init();
        GasChain.init();
        GlueChain.init();
        HexanitrohexaaxaisowurtzitaneChain.init();
        ZylonChain.init();
        MiscRecipes.init();
        MagicChain.init();
        RecipeConflicts.init();
        removeRecipes.init();
        SpinnerHelper.init();
        AluminiumLine.init();
        CoilWire.init();
        GCYSMetaTileEntityLoader.init();
        GCYSBlockRecipeLoader.init();
        BoulesRecipes.init();
        FEPChain.init();
        NdYAGChain.init();
        FireboxCasingRecipes.register();
        GrapheneChain.init();
        NanoCoatingRecipes.init();
        PreciousMetalChain.init();
        MiningDrill.init();
        HydrogenPeroxideChain.init();
        PETChain.init();
        AcetyleneChain.init();
        TurpentineChain.init();
        EDTAChain.init();
        EtchingMaterialsChain.init();
        OilProcessing.init();
        DimethylformamideChain.init();
        CleanWaterChain.init();
        KaptonChain.init();
        PowerSupply.init();
        ProgrammableCircuit.init();
        AmmoniaChain.init();
        AdvancedLubricantChain.register();
        DrillingMudChain.register();
        BrineChain.init();
        MethylamineChain.init();
        KevlarChain.init();
        BoronNitrideChain.register();
        BZChain.init();
        PhosphorusChain.init();
        EthyleneGlycolChain.init();
        IodineChain.init();
        PMMAChain.init();
        GalliumNitrideChain.init();
        PhotoresistivesChain.init();
        MagneticsChain.init();
        NanotubesChain.init();
        IsotopesChain.init();
        FullereneChain.init();
        Batteries.init();
        FantasyMaterials.init();
        SimpleMaterials.init();
        PedotChain.init();
        SeleniumTelluriumChain.init();
        BiochemChains.init();
        BiologyRecipe.init();
        PhotoresistChains.init();
        PetrochemRecipes.init();
        MaterialOreChains.init();
        LubricantChains.init();
        PEEKChain.init();
        Electrolyzer.init();
        CPULine.init();
        GTComponentsRemove.init();
        SwarmRecipeHandler.runRecipeGeneration();
        SwarmRecipeHandler.runRecipeBreeding();
        CircuitryMaterialChains.init();
        OilChains.init();
        DrumRecipes.init();
        CrateRecipes.init();
        PCBline.init();
        NanotubesChain.init();
        initCircuits();
        initOreProcessing();
        ComponentRecipes.init();
        AutoChiselRecipeLoader.init();
        ChiselMachineRecipeLoader.init();
        PreciseAssemblerChain.init();
    }
    private static void initOreProcessing() {
        PlatinumGroupProcessing.init();
        RareEarthProcessing.init();
        TungstenProcessing.init();
        GermaniumProcessing.init();
        NiobiumTantalumChain.init();
        MolybdenumProcessing.init();
        ThalliumProcessing.init();
        TaraniumProcessing.init();
        FullerenePolymerMatrixChain.init();
        RubidiumProcessing.init();
    }
    private static void initCircuits() {
        PrimitiveCircuits.init();
        CrystalCircuits.init();
        WetwareCircuits.init();
        GoowareCircuits.init();
        OpticalCircuits.init();
        SpintronicCircuits.init();
    }
}
